# 测试我们的算法

In [27]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [28]:
# 加载数据
iris = datasets.load_iris()

In [29]:
X = iris.data
y = iris.target

In [30]:
X.shape

(150, 4)

In [31]:
y.shape

(150,)

In [32]:
# X 的索引随机排列
shuffle_indexs = np.random.permutation(len(X))

In [33]:
shuffle_indexs

array([116,  68, 127,  46, 128,  23,  15,  82,  39,  62, 132,  12, 104,
        99, 107,  81, 146,  71,  25, 141, 145, 102,  33,  79,  75, 144,
       135, 108,  64, 105, 140,  93,  24,  78,  61, 148,  63, 136,  97,
        96,  52,  47,  36,  42, 113,  98, 143,  18,  92,  13,  91,  65,
        34,  49, 129, 125,  66,  95,  84, 111,  51,  67,  80,   1,   9,
        40, 115,  58,  16,  69,  32,  21, 118,  87,   4,  73, 120,  30,
        85,  57, 119, 117, 139,  94,   0,  35,  89,  43, 112, 138, 147,
        86,  55,  41, 110,  88,  60,  45,   3,  11,  59, 142,  76,  26,
        20, 109,   5,  44, 126, 101,  27,  90,  74,  77,  29,  31,  70,
       149,  22,   7,   2, 106, 103, 114,  37, 100,  50,  56, 123,  14,
        48,   6,   8,  28,  53,  72, 131, 137,  19, 122, 130, 134,  10,
        17, 121,  83,  38, 133,  54, 124])

In [34]:
# 测试数据集
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [35]:
test_size

30

In [36]:
# 测试和训练数据集索引的划分
test_indexs = shuffle_indexs[:test_size] # 前test_size个
train_indexs = shuffle_indexs[test_size:] # 剩余

In [37]:
# 训练数据集
X_train = X[train_indexs]
y_train = y[train_indexs]

# 测试数据集
X_test = X[test_indexs]
y_test = X[test_indexs]

In [38]:
# 训练和测试数据集的样式
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30, 4)


# 使用算法train_test_split

In [52]:
# 引入train_test_split
%run C:\Learning\jupyter-notebook\ml\playML\model_selection.py

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [54]:
# 训练和测试数据集的样式
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [70]:
# 引入自己写的KNN算法
%run C:\Learning\jupyter-notebook\ml\playML\KNN.py

In [71]:
# 创建对象
my_knn_clf = KNNClassifier(k=3)

In [72]:
# 拟合
my_knn_clf.fit(X_train, y_train)

KNN(k=3

In [73]:
# 预测
y_predict = my_knn_clf.predict(X_test)

In [74]:
y_predict

array([2, 0, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 1, 0, 0, 2, 2, 2, 1,
       1, 2, 2, 1, 1, 0, 2, 2])

In [75]:
y_test

array([2, 0, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 1, 0, 0, 2, 2, 2, 1,
       1, 2, 2, 1, 1, 0, 2, 2])

In [76]:
# 自己写的KNN算法与train_test_split比较
sum(y_predict == y_test)

30

In [77]:
# 正确率
sum(y_predict == y_test) / len(y_test)

1.0

# sklearn中的train_test_split

In [78]:
from sklearn.model_selection import train_test_split

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [80]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [81]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
